DataGen:
  ops:
    - randaugment
    - random_erasing
    - gridmask
    - tia_distort
    - tia_stretch
    - tia_perspective
  data_dir: "demo/clas_data"
  label_file: "demo/clas_data/train_list.txt"
  aug_file: "labels/test.txt"
  out_dir: "test"
  gen_ratio: 0
  gen_num: 5
  size: 224

FeatureExtract:
  config: "deploy/configs/ppcv/feature_extract.yaml"
  thresh: 0.5
  file_out: "tmp/rm_repeat.txt"

  # indexing engine config
IndexProcess:
  index_method: "HNSW32" # supported: HNSW32, IVF, Flat
  image_root: "./test"
  index_dir: "./augdata/all_aug"
  data_file:  "./labels/test.txt"
  index_operation: "new" # suported: "append", "remove", "new"
  delimiter: " "
  dist_type: "IP"
  embedding_size: 512
  batch_size: 32
  return_k: 5
  score_thres: 0.5

BigModel:
  model_type: cls  # support(cls / ocr)
  config: "deploy/configs/ppcv/big_model_classification.yaml"
  batch_size: 8
  thresh: 0.1
  final_label: "high_socre_label.txt"
